# Generated by Django 5.2.17 on 2026-08-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workflow_assigned_to_workflowactivity_workflowmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
